'use strict';
module.exports = {
  inventoryRequest: {
    startDate: { type: 'string', description: '开始日期', required: false, example: '2020-05-09' },
    endDate: { type: 'string', description: '结束日期', required: false, example: '2020-05-10' },
    startStation: { type: 'string', description: '始发站', required: false, example: '' },
    endStation: { type: 'string', description: '到货站', required: false, example: '' },
    customer: { type: 'string', description: '托运人', required: false, example: '' },
    consignee: { type: 'string', description: '收货人', required: false, example: '' },
    payment: { type: 'string', description: '付款方式', required: false, example: '' },
    state: { type: 'string', description: '结单状态', required: false, example: '' },
    goods: { type: 'string', description: '货物名称', required: false, example: '' },
    dh: { type: 'string', description: '货运单号', required: false, example: '运单号' },
    i: { type: 'number', description: '页码', required: true, example: 1 },
  },
  inventoryResponse: {
    status: {
      type: 'number',
      example: 1,
    },
    res: {
      type: 'string',
      example: [
        {
          id: 5,
          kddh: 'KD2005110001',
          startStation: '广东1',
          endStation: '上海2',
          carNumber: '粤A-4552',
          driver: '',
          register: '卾A6336挂',
          remark: '阿萨达撒',
          date: '2020-05-11',
          date2: '2020-05-11',
          state: 0,
          dataList: [
            {
              id: 5,
              jlid: 0,
              kddh: 'KD2005110001',
              customerName: '托运人2',
              consignee: '收货人',
              dh: '运单号',
              dh2: '单号',
              endStation: '到货站',
              consigneeAddress: '收货地址',
              num: 22,
              quantity: 555,
              collection: 5454,
              insured: 54,
              otherPrice: 65,
              payee: '收款人',
              receipts: 44,
              date: '2020-05-10',
              sum: 10,
              discount: 555,
              transferFee: 555,
              deliveryFee: 555,
              payment: '提付',
              state: 0,
              remark: '备注',
            },
            {
              id: 6,
              jlid: 0,
              kddh: 'KD2005110001',
              customerName: '托运人',
              consignee: '收货人',
              dh: '运单号',
              dh2: '单号',
              endStation: '到货站',
              consigneeAddress: '收货地址',
              num: 22,
              quantity: 555,
              collection: 5454,
              insured: 54,
              otherPrice: 65,
              payee: '收款人',
              receipts: 44,
              date: '2020-05-10',
              sum: 10,
              discount: 555,
              transferFee: 555,
              deliveryFee: 555,
              payment: '提付',
              state: 0,
              remark: '备注',
            },
          ],
        },
      ],
    },
    total: {
      type: 'number',
      example: 3,
    },
  },

  inventoryAddRequest: {
    date: { type: 'string', description: '开单日期', required: true, example: '2020-05-11' },
    creator: { type: 'string', description: '制单人', required: true, example: '王五' },
    startStation: { type: 'string', description: '发货点', required: true, example: '广东' },
    endStation: { type: 'string', description: '卸货点', required: true, example: '上海' },
    carNumber: { type: 'string', description: '车号', required: true, example: '粤A-4552' },
    driver: { type: 'string', description: '司机', required: true, example: '王五' },
    register: { type: 'string', description: '挂号', required: true, example: '卾A6336挂' },
    remark: { type: 'string', description: '备注', required: true, example: '阿萨达撒' },
    state: { type: 'number', description: '结单状态', required: false, example: 0 },
    dataList: { type: 'string', description: '制单人', required: true, example: [
      { customerName: '托运人', consignee: '收货人', dh: '运单号', dh2: '单号', jlid: 0, state: 0, endStation: '到货站', consigneeAddress: '收货地址', num: 22, quantity: 555, collection: 5454, insured: 54, otherPrice: 65, payee: '收款人', receipts: 44, date: '2020-05-10', sum: 10, transferFee: 555, deliveryFee: 555, discount: 555, payment: '提付', remark: '备注' },
      { customerName: '托运人', consignee: '收货人', dh: '运单号', dh2: '单号', jlid: 0, state: 0, endStation: '到货站', consigneeAddress: '收货地址', num: 22, quantity: 555, collection: 5454, insured: 54, otherPrice: 65, payee: '收款人', receipts: 44, date: '2020-05-10', sum: 10, transferFee: 555, deliveryFee: 555, discount: 555, payment: '提付', remark: '备注' },
    ] },
  },
  inventoryAddResponse: {
    status: {
      type: 'number',
      example: 1,
    },
  },

  inventoryUpdateRequest: {
    kddh: { type: 'string', description: '开单日期', required: true, example: 'KD2005110001' },
    date: { type: 'string', description: '开单日期', required: true, example: '2020-05-11' },
    creator: { type: 'string', description: '制单人', required: true, example: '王五' },
    startStation: { type: 'string', description: '发货点', required: true, example: '广东' },
    endStation: { type: 'string', description: '卸货点', required: true, example: '上海' },
    carNumber: { type: 'string', description: '车号', required: true, example: '粤A-4552' },
    driver: { type: 'string', description: '司机', required: true, example: '王五' },
    register: { type: 'string', description: '挂号', required: true, example: '卾A6336挂' },
    remark: { type: 'string', description: '备注', required: true, example: '阿萨达撒' },
    state: { type: 'string', description: '结单状态', required: false, example: '' },
    dataList: { type: 'string', description: '制单人', required: true, example: [
      { customerName: '托运人', consignee: '收货人', dh: '运单号', dh2: '单号', state: 0, jlid: 0, endStation: '到货站', consigneeAddress: '收货地址', num: 22, quantity: 555, collection: 5454, insured: 54, otherPrice: 65, payee: '收款人', receipts: 44, date: '2020-05-10', sum: 10, transferFee: 555, deliveryFee: 555, discount: 555, payment: '提付', remark: '备注' },
      { customerName: '托运人', consignee: '收货人', dh: '运单号', dh2: '单号', state: 0, jlid: 0, endStation: '到货站', consigneeAddress: '收货地址', num: 22, quantity: 555, collection: 5454, insured: 54, otherPrice: 65, payee: '收款人', receipts: 44, date: '2020-05-10', sum: 10, transferFee: 555, deliveryFee: 555, discount: 555, payment: '提付', remark: '备注' },
    ] },
  },
  inventoryUpdateResponse: {
    status: {
      type: 'number',
      example: 1,
    },
  },

  inventoryDeleteRequest: {
    kddh: { type: 'string', description: '单号', required: true, example: 'KD2005110001' },
  },
  inventoryDeleteResponse: {
    status: {
      type: 'number',
      example: 1,
    },
  },
};
