'use strict';
module.exports = {
  transportRequest: {
    startDate: { type: 'string', description: '开始日期', required: false, example: '2020-05-09' },
    endDate: { type: 'string', description: '结束日期', required: false, example: '2020-05-10' },
    startStation: { type: 'string', description: '始发站', required: false, example: '宁波' },
    endStation: { type: 'string', description: '到货站', required: false, example: '广东' },
    customerName: { type: 'string', description: '托运人', required: false, example: '老黄' },
    consignee: { type: 'string', description: '收货人', required: false, example: '老王' },
    payment: { type: 'string', description: '付款方式', required: false, example: '提付' },
    state: { type: 'string', description: '结单状态', required: false, example: '未结单' },
    goods: { type: 'string', description: '货物名称', required: false, example: 'AA' },
    i: { type: 'number', description: '页码', required: true, example: 1 },
  },
  transportResponse: {
    status: {
      type: 'number',
      example: 1,
    },
    res: {
      type: 'string',
      example: [
        {
          id: 31,
          dh: 'ASF-GFG',
          date: '2020-05-10',
          lsh: '1',
          creator: '王五',
          startStation: '王五',
          endStation: '王五',
          consignee: '王五',
          consigneePhone: '王五',
          consigneeAddress: '王五',
          customerName: '王五',
          customerPhone: '王五',
          customerAddress: '王五',
          remark: '王五',
          imaginaryPiece: 454,
          imaginaryPercent: 4545,
          payment: '王五',
          insured: 4564,
          insuredSum: 64545,
          insuredRatio: 6454,
          collection: 487,
          sum: 45654,
          state: '王五',
          position: '海南',
          dataList: [
            {
              id: 120,
              dh: 'ASF-GFG',
              goods: '货物',
              unit: '单位',
              num: 456,
              quantity: 365,
              unfigure: 456,
              price: 22,
              money: 555,
              discount: 5454,
              transferFee: 54,
              deliveryFee: 65,
              otherPrice: 10,
              remark: '备注',
            },
            {
              id: 121,
              dh: 'ASF-GFG',
              goods: '货物',
              unit: '单位',
              num: 5456,
              quantity: 45654,
              unfigure: 45645,
              price: 22,
              money: 555,
              discount: 5454,
              transferFee: 54,
              deliveryFee: 65,
              otherPrice: 10,
              remark: '备注',
            },
          ],
        },
        {
          id: 32,
          dh: 'ASF-GF',
          date: '2020-05-10',
          lsh: '1',
          creator: '王五',
          startStation: '王五',
          endStation: '王五',
          consignee: '王五',
          consigneePhone: '王五',
          consigneeAddress: '王五',
          customerName: '王五',
          customerPhone: '王五',
          customerAddress: '王五',
          remark: '王五',
          imaginaryPiece: 454,
          imaginaryPercent: 4545,
          payment: '王五',
          insured: 4564,
          insuredSum: 64545,
          insuredRatio: 6454,
          collection: 487,
          sum: 45654,
          state: '王五',
          position: '海南',
          dataList: [
            {
              id: 114,
              dh: 'ASF-GF',
              goods: '货',
              unit: '单位',
              num: 456,
              quantity: 365,
              unfigure: 45,
              price: 22,
              money: 555,
              discount: 5454,
              transferFee: 54,
              deliveryFee: 65,
              otherPrice: 10,
              remark: '备注',
            },
            {
              id: 115,
              dh: 'ASF-GF',
              goods: '货',
              unit: '单位',
              num: 5456,
              quantity: 45654,
              unfigure: 45,
              price: 22,
              money: 555,
              discount: 5454,
              transferFee: 54,
              deliveryFee: 65,
              otherPrice: 10,
              remark: '备注',
            },
          ],
        },
      ],
    },
    total: {
      type: 'number',
      example: 3,
    },
  },

  transportAddRequest: {
    dh: { type: 'string', description: '单号', required: true, example: 'ASF-GFG' },
    date: { type: 'string', description: '日期', required: true, example: '2020-05-10' },
    lsh: { type: 'string', description: '流水号', required: true, example: '1' },
    creator: { type: 'string', description: '制单人', required: true, example: '王五' },
    startStation: { type: 'string', description: '制单人', required: true, example: '王五' },
    endStation: { type: 'string', description: '制单人', required: true, example: '王五' },
    consignee: { type: 'string', description: '制单人', required: true, example: '王五' },
    consigneePhone: { type: 'string', description: '制单人', required: true, example: '王五' },
    consigneeAddress: { type: 'string', description: '制单人', required: true, example: '王五' },
    customerName: { type: 'string', description: '制单人', required: true, example: '王五' },
    customerPhone: { type: 'string', description: '制单人', required: true, example: '王五' },
    customerAddress: { type: 'string', description: '制单人', required: true, example: '王五' },
    remark: { type: 'string', description: '制单人', required: true, example: '王五' },
    imaginaryPiece: { type: 'number', description: '制单人', required: true, example: 454 },
    imaginaryPercent: { type: 'number', description: '制单人', required: true, example: 4545 },
    payment: { type: 'string', description: '制单人', required: true, example: '王五' },
    insured: { type: 'number', description: '制单人', required: true, example: 4564 },
    insuredSum: { type: 'number', description: '制单人', required: true, example: 64545 },
    insuredRatio: { type: 'number', description: '制单人', required: true, example: 6454 },
    collection: { type: 'number', description: '制单人', required: true, example: 487 },
    sum: { type: 'number', description: '制单人', required: true, example: 45654 },
    position: { type: 'string', description: '现在位置', required: true, example: '海南' },
    dataList: { type: 'string', description: '记录', required: true, example: [
      { dh: 'ASF-GFG', goods: '货物', unit: '单位', num: 456, state: 0, quantity: 365, unfigure: 45, price: 22, money: 555, discount: 5454, transferFee: 54, deliveryFee: 65, otherPrice: 10, remark: '备注' },
      { dh: 'ASF-GFG', goods: '货物', unit: '单位', num: 5456, state: 0, quantity: 45654, unfigure: 45, price: 22, money: 555, discount: 5454, transferFee: 54, deliveryFee: 65, otherPrice: 10, remark: '备注' },
    ] },
  },
  transportAddResponse: {
    status: {
      type: 'number',
      example: 1,
    },
    msg: {
      type: 'string',
      example: '保存成功！',
    },
    res: {
      type: 'string',
      example: {
        id: 42,
        dh: 'ASF-GF8G555',
        date: '2020-05-10',
        lsh: 5,
        creator: '王五',
        startStation: '王五',
        endStation: '王五',
        consignee: '王五',
        consigneePhone: '王五',
        consigneeAddress: '王五',
        customerName: '王五55556765',
        customerPhone: '王五',
        customerAddress: '王五',
        remark: '王五',
        imaginaryPiece: 454,
        imaginaryPercent: 4545,
        payment: '王五',
        insured: 4564,
        insuredSum: 64545,
        insuredRatio: 6454,
        collection: 487,
        sum: 45654,
      },
    },
  },

  transportUpdateRequest: {
    dh: { type: 'string', description: '单号', required: true, example: 'ASF-GFG' },
    date: { type: 'string', description: '日期', required: true, example: '2020-05-10' },
    lsh: { type: 'string', description: '流水号', required: true, example: '1' },
    creator: { type: 'string', description: '制单人', required: true, example: '王五' },
    startStation: { type: 'string', description: '制单人', required: true, example: '王五' },
    endStation: { type: 'string', description: '制单人', required: true, example: '王五' },
    consignee: { type: 'string', description: '制单人', required: true, example: '王五' },
    consigneePhone: { type: 'string', description: '制单人', required: true, example: '王五' },
    consigneeAddress: { type: 'string', description: '制单人', required: true, example: '王五' },
    customerName: { type: 'string', description: '制单人', required: true, example: '王五' },
    customerPhone: { type: 'string', description: '制单人', required: true, example: '王五' },
    customerAddress: { type: 'string', description: '制单人', required: true, example: '王五' },
    remark: { type: 'string', description: '制单人', required: true, example: '王五' },
    imaginaryPiece: { type: 'number', description: '制单人', required: true, example: 454 },
    imaginaryPercent: { type: 'number', description: '制单人', required: true, example: 4545 },
    payment: { type: 'string', description: '制单人', required: true, example: '王五' },
    insured: { type: 'number', description: '制单人', required: true, example: 4564 },
    insuredSum: { type: 'number', description: '制单人', required: true, example: 64545 },
    insuredRatio: { type: 'number', description: '制单人', required: true, example: 6454 },
    collection: { type: 'number', description: '制单人', required: true, example: 487 },
    sum: { type: 'number', description: '制单人', required: true, example: 45654 },
    position: { type: 'string', description: '现在位置', required: true, example: '海南' },
    dataList: { type: 'string', description: '记录', required: true, example: [
      { dh: 'ASF-GFG', goods: '货物', unit: '单位', num: 456, state: 0, quantity: 365, unfigure: 456, price: 22, money: 555, discount: 5454, transferFee: 54, deliveryFee: 65, otherPrice: 10, remark: '备注' },
      { dh: 'ASF-GFG', goods: '货物', unit: '单位', num: 5456, state: 0, quantity: 45654, unfigure: 45645, price: 22, money: 555, discount: 5454, transferFee: 54, deliveryFee: 65, otherPrice: 10, remark: '备注' },
    ] },
  },
  transportUpdateResponse: {
    status: {
      type: 'number',
      example: 1,
    },
    lsh: {
      type: 'string',
      example: 1,
    },
    msg: {
      type: 'string',
      example: '保存成功！',
    },
  },

  transportDeleteRequest: {
    dh: { type: 'string', description: '单号', required: true, example: 'ASF-GFG' },
  },
  transportDeleteResponse: {
    status: {
      type: 'number',
      example: 1,
    },
  },
};
